
service: mymusicapp

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  enviorment:
    tableName: ${self:custom.tableName}
  iamRoleStatments:
        - Effect: Allow
          Action:
                - dynamodb:* 
          Resource: '*'

plugins:
  - serverless-s3-sync

custom:
  tableName: Artist
  s3Sync:
    - bucketName: bucketofmusic44
      localDir: UploadData

functions:
        getUser:
            handler: lambdas/endpoints/getUser.handler
            events:
                - http:
                      path: get-user/{ID}
                      method: GET
                      cors: true

        getArtist:
            handler: lambdas/endpoints/getArtist.handler
            events:
                - http:
                      path: get-Artist/{ID}
                      method: GET
                      cors: true


resources:
    Resources:
        DemoBucketUpload:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: bucketofmusic44
        MyDynamoDbTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: ID
                      AttributeType: S
                KeySchema:
                    - AttributeName: ID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST